export {default as NavBar} from "./NavBar"
export {default as Landing} from "./Landing"
export {default as Projects} from "./Projects"
export {default as Skills} from "./Skills"
export {default as Contact} from "./Contact"